#!/bin/bash -
# SPDX-FileCopyrightText: <text> © 2020 Alan D. Salewski <ads@salewski.email> </text>
#
# SPDX-License-Identifier: GPL-2.0-or-later

# curl-gh-fout-q: Wrapper around the 'curl-gh-fout' program to "layer in"
# configuration to suppress the curl(1) progress meter and other non-error
# output.
#
# Of the 'curl-gh*' set of programs, this one most closely mimics the behavior
# of the various 'ads-github-tools' programs. The the HTTP response body will
# be written to the user-specified filepath, and the HTTP response code will
# be emitted on stdout.
#
# The curl progress meter, etc., will be suppressed. If you do wish to see
# that output, you may be interested in the 'curl-gh-fout' script, instead
# (which this one wraps).
#
# Invokes curl(1) configured to talk to GitHub over TLS 1.2 (or
# higher). Basically sets up command line options to curl(1) in a way similar
# to how it is done by the 'ads-github-tools', for easy interactive use on the
# command line.
#
# The user must provide two required (positional) params:
#
#     1. GitHub URL (or path; see below) to invoke
#
#     2. Output filepath for HTTP response body
#
# As a common-case optimization, if the value provided for the GitHub URL
# starts with a '/' character, then it will be interpreted as the start of a
# URL path that will be prepended to:
#
#     https://api.github.com
#
# This saves the user from having to remember and specify that unchanging URL
# base, and can also save some typing. Thus, the following two invocations are
# effectively identical:
#
#     $ curl-gh-fout-q 'https://api.github.com/user/repos' '/tmp/rsp.out'
#
#     $ curl-gh-fout-q '/user/repos' '/tmp/rsp.out'
#
# As a special case, if the very first option on the command line is
# '--no-act', then the curl command line that would otherwise be run is simply
# printed to stdout. This is useful not only for understanding what the tool
# is doing, but also for copying the command for use for manual editing on the
# command line (sometimes you want /most/ of the behavior here, but not all of
# it...)
#
# Any additional command line options will be passed through to curl(1). Some
# curl options might interfere with the correct functioning of this program;
# no attempt is made to detect such conflicts.
#
# Note that no particular request method (GET, POST, PUT, ...) is specified by
# the default options (which means that the default curl behavior of
# defaulting to GET will be used) unless a user-provided option causes some
# other method to be used. This is just like when using curl directly.
#
#
# Usage:
#     curl-gh-fout-q [--no-act] GH_URL OUTPUT_FPATH [CURL_OPT...] 
#
#
# HINT: The mnemonic for remembering the order of the params is that they
#       resemble the order of 'cp(1)':
#
#           $ cp SOURCE DEST
#
#       Conceptually, you are taking the data from (emitted by) the URL, and
#       storing it in OUTPUT_FPATH:
#
#           $ curl-gh-fout-q GH_URL OUTPUT_FPATH
#
#
# See also:
#
#     * curl-gh
#
#     * curl-gh-fout
#
#     * GitHub v3 API:
#         - https://developer.github.com/v3/
#         - https://docs.github.com/v3/
#
declare -r PROG='curl-gh-fout-q'

declare -r MAINTAINER='Alan D. Salewski <ads@salewski.email>'

BE_VERBOSE=false
# BE_VERBOSE=true

DEBUGGING=false
# DEBUGGING=true

f_print_help () {

    cat <<EOF
usage: ${PROG} GITHUB_URL OUTPUT_FILE [CURL_OPT...]

Invokes curl-gh-fout, which itself wraps curl(1) configured to invoke the
GitHub v3 API. The HTTP response output is written to OUTPUT_FILE. The HTTP
response code is written to stdout.

Report bugs to ${MAINTAINER}.
EOF
}


req_cnt=2
if test "$1" = '--no-act'; then
    req_cnt=3
fi

# We will not shift-off the first two arguments; we will just ensure that they
# are present (and complain otherwise).
#
if test $# -lt $req_cnt; then
    printf "${PROG} (error): required OUTPUT_FILE param missing; bailing out\n" 1>&2
    f_print_help 1>&2
    exit 1
fi
if test $# -lt $(( $req_cnt - 1 )); then
    printf "${PROG} (error): required GITHUB_URL param missing; bailing out\n" 1>&2
    f_print_help 1>&2
    exit 1
fi


# For needed internal progs, we will just expect them to be installed "next
# to" the current program.
#
# Note that the mechanism used here needs to work both "in-tree" and when
# installed. When working in-tree, the other in-tree versions of our internal
# tools must be found first (even if the tools are installed on the system).
#
t_script_dir=${0%/*}
AGH_CONTRIB_CURL_GH_FOUT_PROG="${t_script_dir}/curl-gh-fout"

declare -a NEEDED_INTERNAL_PROGS=(
    "${AGH_CONTRIB_CURL_GH_FOUT_PROG}"
)
for t_int_tool in "${NEEDED_INTERNAL_PROGS[@]}"; do
    if test -x "${t_int_tool}"; then :; else
        printf "${PROG} (error): was unable to locate internal tool: \"%s\"; bailing out\n" "${t_int_tool}" 1>&2
        exit 1
    fi
    if $DEBUGGING; then
        printf "${PROG} (debug): found internal tool: %s\n" "${t_int_tool}" 1>&2
    fi
done

# These options will (eventually) get passed-through to curl
declare -a ADDL_CURL_OPTS=()

# This disables output of curl's progress meter /and/ output of error messages...
ADDL_CURL_OPTS+=( '--silent' )
# ...but this re-enables output of the error messages...
ADDL_CURL_OPTS+=( '--show-error' )

# ...and write the HTTP response status to stdout. This allows for robust
# error handling. Also, we cannot really know how to interpret the output
# returned from the remote server until we have examined (at least) the HTTP
# response code.
#
ADDL_CURL_OPTS+=( '--write-out'  )
ADDL_CURL_OPTS+=( '%{http_code}' )

exec "${AGH_CONTRIB_CURL_GH_FOUT_PROG}" "$@" "${ADDL_CURL_OPTS[@]}"
